#!/bin/bash
#SBATCH --job-name=distsweep
#SBATCH --ntasks=16
#SBATCH --mem-per-cpu=3096
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=1

#SBATCH --error="slurm-%j.err"
#SBATCH --output="slurm-%j.out"

#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=dche145@stduent.monash.edu

source /home/${USER}/.bashrc

python my_meep/main.py "config 1" 
python my_meep/main.py "config 2" 
python my_meep/main.py "config 3" 
python my_meep/main.py "config 4" 
